First commit bigint-opt
ST-1580/first-term pull request #4
Opened 2020-07-04 20:59 UTC by ST-1580

2020-07-07 09:42 UTC, kt-cpp requested changes
В целом неплохо, но ещё несколько общих косяков:
* Не хватает свежих тестов на бигинт
* Какие-то странные изменения в gtest

2020-07-07 09:42 UTC, kt-cpp commented on bigint-optimized/long_buf.h
> +    }
[minor]  Для пустого тела конструктора лучше писать просто `{}`

2020-07-07 09:42 UTC, kt-cpp commented on bigint-optimized/long_buf.h
> +    }
[minor] Для пустого тела конструктора лучше писать просто {}

2020-07-07 09:42 UTC, kt-cpp commented on bigint-optimized/long_buf.h
> +    }
Почему просто не перегрузки оператора []?

2020-07-07 09:42 UTC, kt-cpp commented on bigint-optimized/long_buf.h
> +    uint32_t const& back() {
Если возвращать ссылку на константу, то почему саму функцию не сделать константной?

2020-07-07 09:42 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +    static const size_t MAX_SIZE = 2;
[minor] `constexpr`

2020-07-07 09:42 UTC, kt-cpp commented on bigint-optimized/long_buf.h
> +    long_buf* make_data() {
[minor] Название как-то совсем не соответствует контракту функции

2020-07-07 09:42 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +    }
Это можно написать заметно эффективнее. Сейчас на каждый чих происходит куча проверок, а можно только один раз проверить в этой функции

2020-07-07 09:42 UTC, kt-cpp commented on bigint-optimized/long_buf.h
> +    long_buf(std::vector<uint32_t> const a) : ref_counter(1), v(a) {
Консантный вектор по значению?

2020-07-07 09:42 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +                }
У вектора есть конструктор от двух итераторов. Плюс можно это вынести прям в конструктор `long buff`, чтобы уменьшить копирования

2020-07-07 09:42 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +            }
Для `uint32_t` нет смысла вызывать деструктор

2020-07-07 09:42 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +            long_data = new long_buf(*a.long_data);
Тут нужно не копировать, а просто увеличить счётчик ссылок

2020-07-08 09:59 UTC, sorokin commented
```
    long_buf(std::vector<uint32_t> a) : ref_counter(1), v(a) {}
```
`const&`? Или можно принять по значению и потом сделать `move`.

2020-07-08 09:59 UTC, sorokin commented
```
long_buf(uint32_t a[], size_t sz) : ref_counter(1), v(a, a + sz) {}
```
const?

2020-10-18 19:08 UTC, merged